name: Context
on:
  push:
  pull_request:
env:
  EVENT: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: 'if-push'
        if: ${{ env.EVENT == 'push' }}
        run: echo "c'est un $EVENT"
      - name: 'if-pull_request'
        if: ${{ env.EVENT == 'pull_request' }}
        run: echo "c'est un $EVENT"