name: manual-job
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: manually-triggered
        run: echo "This workflows was triggered manually"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: auto-triggered
        run: echo "this one is auto launched"